---
kind: pipeline
type: kubernetes
name: pr

trigger:
  event:
  - pull_request

environment:
  STATEDIR: /drone/src/state

steps:
  - name: fetch tags
    image: docker:git
    commands:
      - git fetch --tags
  - name: wait for docker
    image: docker
    commands:
      - timeout 15s /bin/sh -c 'while [ ! -S /var/run/docker.sock ]; do sleep 1; done'
      - docker version
    volumes:
      - name: dockersock
        path: /var/run
  - name: download binaries
    image: docker:git
    commands:
      - apk add --no-cache make curl
      - make download-binaries
  - name: login to opscenter
    image: docker:git
    environment:
      OPS_URL:
        from_secret: OPS_URL
      API_KEY:
        from_secret: OPS_API_KEY_RO
    commands:
      # tele is built against glibc. Alpine's musl libc is glibc compatible, but needs to be linked into place.
      - apk add --no-cache libc6-compat
      - ./bin/tele login --state-dir=$STATEDIR --hub $OPS_URL --token=$API_KEY
  - name: build
    image: docker:git
    environment:
      OPS_URL:
        from_secret: OPS_URL
    commands:
      - apk add --no-cache make libc6-compat
      # add binaries downloaded in "download binaries" step to path
      - export PATH=$PATH:$(pwd)/bin
      - export EXTRA_GRAVITY_OPTIONS=--state-dir=$STATEDIR
      - make build-app
    volumes:
      - name: dockersock
        path: /var/run

services:
  - name: run docker daemon
    image: docker:dind
    privileged: true
    volumes:
      - name: dockersock
        path: /var/run

volumes:
  - name: dockersock
    temp: {}
---
kind: signature
hmac: a8e8a65ff76b3b29c82147758b930c97614c295df9fd9f9ffb059e0e88314e63

...
