apiVersion: batch/v1
kind: Job
metadata:
  name: cassandra-password
  namespace: default
spec:
  template:
    metadata:
      name: cassandra-password
    spec:
      restartPolicy: OnFailure
      containers:
        - image: cassandra:latest
          name: cassandra-password
          command: ["/cassandra-password-alter.sh"]
          env:
            - name: CASSANDRA_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: cassandra-password
                  key: cassandra
          volumeMounts:
            - name: cassandra-ssl
              mountPath: /etc/ssl/cassandra
      volumes:
        - name: cassandra-ssl
          secret:
            secretName: cassandra-ssl
