apiVersion: v1
kind: Service
metadata:
  name: cassandra
  namespace: default
  labels:
    app: pithos
spec:
  ports:
    - port: 9042
      name: cql
    - port: 9160
      name: rpc
    - port: 7199
      name: jmx
  selector:
    app: pithos
    pithos-role: cassandra
---
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: cassandra
  namespace: default
  labels:
    app: pithos
    pithos-role: cassandra
spec:
  template:
    metadata:
      labels:
        app: pithos
        pithos-role: cassandra
    spec:
      nodeSelector:
        pithos-role: node
      containers:
        - image: cassandra:latest
          name: cassandra
          imagePullPolicy: Always
          env:
            - name: MAX_HEAP_SIZE
              value: 512M
            - name: HEAP_NEWSIZE
              value: 100M
            - name: CASSANDRA_OPEN_JMX
              value: "true"
            - name: CASSANDRA_CLUSTER_NAME
              value: Pithos Cluster
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
          ports:
            - containerPort: 7000
              name: intra-node
            - containerPort: 7011
              name: tls-intra-node
            - containerPort: 7199
              name: jmx
            - containerPort: 9042
              name: cql
            - containerPort: 9160
              name: rpc
          volumeMounts:
            - name: data
              mountPath: /cassandra_data
            - name: cassandra-cfg
              mountPath: /etc/cassandra
            - name: cluster-ca
              mountPath: /etc/ssl/cluster-ca
            - name: cluster-default-ssl
              mountPath: /etc/ssl/cluster-default
            - name: cassandra-ssl
              mountPath: /etc/ssl/cassandra
      volumes:
        - name: data
          hostPath:
            path: /var/lib/data/pithos
        - name: cassandra-cfg
          configMap:
            name: cassandra-cfg
        - name: cluster-ca
          secret:
            secretName: cluster-ca
        - name: cluster-default-ssl
          secret:
            secretName: cluster-default-ssl
        - name: cassandra-ssl
          secret:
            secretName: cassandra-ssl
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: cassandra-utils
  namespace: default
  labels:
    app: pithos
    pithos-role: cassandra-utils
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: pithos
        pithos-role: cassandra-utils
    spec:
      nodeSelector:
        pithos-role: node
      containers:
      - image: cassandra:latest
        name: cassandra-utils
        command: ["/usr/bin/dumb-init", "/usr/sbin/start-utils.sh"]
        imagePullPolicy: Always
        env:
          - name: CRON_SCHEDULE
            value: "15 2 * * *"
