---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: cassandra
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: Role
metadata:
  name: cassandra
  namespace: default
rules:
  - apiGroups:
      - extensions
    resources:
      - podsecuritypolicies
    resourceNames:
      - privileged
    verbs:
      - use
  - apiGroups:
      - ""
    verbs:
      - get
      - list
      - watch
    resources:
      - secrets
    resourceNames:
      - cassandra-ssl
      - cluster-ca
      - cluster-default-ssl
  - apiGroups:
      - ""
    verbs:
      - get
      - list
      - watch
    resources:
      - configmaps
      - endpoints
      - events
      - pods
      - persistentvolumes
      - persistentvolumeclaims
      - services
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: cassandra
  namespace: default
subjects:
  - kind: ServiceAccount
    name: cassandra
    namespace: default
roleRef:
  kind: Role
  name: cassandra
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: Service
metadata:
  name: cassandra
  namespace: default
  labels:
    app: pithos
spec:
  ports:
    - port: 9042
      name: cql
    - port: 9160
      name: rpc
  selector:
    app: pithos
    pithos-role: cassandra
---
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: cassandra
  namespace: default
  labels:
    app: pithos
    pithos-role: cassandra
spec:
  selector:
    matchLabels:
      app: pithos
      pithos-role: cassandra
      component: cassandra
  template:
    metadata:
      labels:
        app: pithos
        pithos-role: cassandra
        component: cassandra
    spec:
      securityContext:
        runAsUser: 0
      serviceAccountName: cassandra
      nodeSelector:
        pithos-role: node
      containers:
        - image: cassandra:latest
          name: cassandra
          imagePullPolicy: Always
          env:
            - name: INFLUXDB_TELEGRAF_USERNAME
              valueFrom:
                secretKeyRef:
                  name: telegraf-influxdb-creds
                  key: username
            - name: INFLUXDB_TELEGRAF_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: telegraf-influxdb-creds
                  key: password
            - name: MAX_HEAP_SIZE
              value: 2048M
            - name: HEAP_NEWSIZE
              value: 256M
            - name: CASSANDRA_OPEN_JMX
              value: "true"
            - name: CASSANDRA_CLUSTER_NAME
              value: Pithos Cluster
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
          ports:
            - containerPort: 7000
              name: intra-node
            - containerPort: 7011
              name: tls-intra-node
            - containerPort: 7199
              name: jmx
            - containerPort: 9042
              name: cql
            - containerPort: 9160
              name: rpc
          volumeMounts:
            - name: data
              mountPath: /cassandra_data
            - name: cluster-ca
              mountPath: /etc/ssl/cluster-ca
            - name: cluster-default-ssl
              mountPath: /etc/ssl/cluster-default
            - name: cassandra-ssl
              mountPath: /etc/ssl/cassandra
        - image: cassandra:latest
          name: cassandra-utils
          command: ["/usr/bin/dumb-init", "/usr/sbin/start-utils.sh"]
          imagePullPolicy: Always
          env:
            - name: CRON_SCHEDULE
              value: "15 2 * * *"
            - name: INFLUXDB_TELEGRAF_USERNAME
              valueFrom:
                secretKeyRef:
                  name: telegraf-influxdb-creds
                  key: username
            - name: INFLUXDB_TELEGRAF_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: telegraf-influxdb-creds
                  key: password
      volumes:
        - name: data
          hostPath:
            path: /var/lib/data/pithos
        - name: cluster-ca
          secret:
            secretName: cluster-ca
        - name: cluster-default-ssl
          secret:
            secretName: cluster-default-ssl
        - name: cassandra-ssl
          secret:
            secretName: cassandra-ssl
---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: telegraf-influxdb-creds
  namespace: default
data:
  username: dGVsZWdyYWY=
  password: c3VwZXJTZWN1cmVQYXNzd29yZA==
