apiVersion: batch/v1
kind: Job
metadata:
  name: cassandra-alter-compaction
  namespace: default
spec:
  template:
    metadata:
      name: cassandra-alter-compaction
    spec:
      securityContext:
        runAsUser: 0
      restartPolicy: OnFailure
      containers:
        - image: cassandra:latest
          name: cassandra-alter-compaction
          command: ["/alter_table_block.sh"]
          volumeMounts:
            - name: cassandra-ssl
              mountPath: /etc/ssl/cassandra
            - name: kubectl
              mountPath: /usr/local/bin/kubectl
      volumes:
        - name: cassandra-ssl
          secret:
            secretName: cassandra-ssl
        - name: kubectl
          hostPath:
            path: /usr/bin/kubectl
