apiVersion: v1
kind: Service
metadata:
  name: pithos
  namespace: default
  labels:
    app: pithos
spec:
  type: NodePort
  ports:
    - port: 443
      targetPort: 18443
      nodePort: 32002
      name: https
  selector:
    app: pithos
    pithos-role: pithos
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: pithos
  namespace: default
  labels:
    app: pithos
    pithos-role: pithos
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: pithos
        pithos-role: pithos
    spec:
      nodeSelector:
        pithos-role: node
      containers:
      - image: pithos-proxy:latest
        name: proxy
        ports:
          - containerPort: 18443
            name: https
        volumeMounts:
          - name: cluster-default-ssl
            mountPath: /etc/cluster-ssl
      - image: pithos:latest
        name: pithos
        ports:
          - containerPort: 18080
            name: pithos
        volumeMounts:
          - name: pithos-cfg
            mountPath: /etc/pithos
      volumes:
        - name: pithos-cfg
          configMap:
            name: pithos-cfg
        - name: cluster-default-ssl
          secret:
            secretName: cluster-default-ssl
