---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: pithos
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: Role
metadata:
  name: pithos
  namespace: default
rules:
  - apiGroups:
      - extensions
    resources:
      - podsecuritypolicies
    resourceNames:
      - privileged
    verbs:
      - use
  - apiGroups:
      - ""
    verbs:
      - get
      - list
      - watch
    resources:
      - secrets
    resourceNames:
      - cluster-default-ssl
  - apiGroups:
      - ""
    verbs:
      - get
      - list
      - watch
    resources:
      - configmaps
      - endpoints
      - events
      - pods
      - persistentvolumes
      - persistentvolumeclaims
      - services
  - apiGroups:
      - ""
    verbs:
      - create
    resources:
      - pods/exec
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: pithos
  namespace: default
subjects:
  - kind: ServiceAccount
    name: pithos
    namespace: default
roleRef:
  kind: Role
  name: pithos
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: Service
metadata:
  name: pithos
  namespace: default
  labels:
    app: pithos
    product: pithos
spec:
  type: NodePort
  ports:
    - port: 443
      targetPort: 18443
      nodePort: 32002
      name: https
  selector:
    app: pithos
    product: pithos
    pithos-role: pithos
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: pithos
  namespace: default
  labels:
    app: pithos
    product: pithos
    pithos-role: pithos
spec:
  selector:
    matchLabels:
      app: pithos
      product: pithos
      pithos-role: pithos
      component: pithos
  replicas: 1
  template:
    metadata:
      labels:
        app: pithos
        product: pithos
        pithos-role: pithos
        component: pithos
    spec:
      serviceAccountName: pithos
      nodeSelector:
        pithos-role: node
      containers:
      - image: pithos:latest
        name: pithos
        ports:
          - containerPort: 18080
            name: pithos
        volumeMounts:
          - name: pithos-cfg
            mountPath: /etc/pithos
      - image: pithos-proxy:latest
        name: proxy
        ports:
          - containerPort: 18443
            name: https
        volumeMounts:
          - name: cluster-default-ssl
            mountPath: /etc/cluster-ssl
      - image: pithos:latest
        name: utils
        command: ["/bin/bash", "-c", "--"]
        args: ["while true; do sleep 6000; done;"]
        env:
          - name: AWS_ACCESS_KEY_ID
            valueFrom:
              secretKeyRef:
                name: pithos-keys
                key: master.key
          - name: AWS_SECRET_ACCESS_KEY
            valueFrom:
              secretKeyRef:
                name: pithos-keys
                key: master.secret
          - name: ENDPOINT
            value: https://pithos.default.svc
        volumeMounts:
          - name: cluster-default-ssl
            mountPath: /etc/cluster-ssl
      volumes:
        - name: pithos-cfg
          configMap:
            name: pithos-cfg
        - name: cluster-default-ssl
          secret:
            secretName: cluster-default-ssl
