apiVersion: batch/v1
kind: Job
metadata:
  name: pithos-initialize
  namespace: default
spec:
  template:
    metadata:
      name: pithos-initialize
    spec:
      restartPolicy: OnFailure
      securityContext:
          runAsUser: -1
      containers:
        - image: cassandra:latest
          name: pithos-initialize
          command: ["/initialize.sh"]
          volumeMounts:
            - name: cassandra-ssl
              mountPath: /etc/ssl/cassandra
            - name: kubectl
              mountPath: /usr/local/bin/kubectl
      volumes:
        - name: cassandra-ssl
          secret:
            secretName: cassandra-ssl
        - name: kubectl
          hostPath:
            path: /usr/bin/kubectl
